import Head from "next/head";
import Slider from "react-slick";

export default function Home() {
  const sliderSettings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };

  return (
    <>
      <Head>
        <title>Josh Hall</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main-bg min-h-screen p-8">
        <h1 className="text-3xl font-bold mb-4">About Me</h1>
        <section className="bg-white bg-opacity-50 p-8 rounded-lg shadow-md">
          <p className="text-lg mb-4">
            As a dedicated full-stack developer, my journey in coding has always
            been driven by a desire to understand and harness the frontier
            technologies. Currently, I find myself captivated by the untapped
            potential of generative AI. This fascination is not merely
            theoretical; I’ve channeled it into creating innovative side
            projects that extend the traditional interactions available with AI
            systems. From using GPT-3 models to generate creative text prompts,
            to employing Stable Diffusion techniques for producing dynamic
            visual representations, I am committed to exploring the ways
            generative AI can revolutionize how we perceive and interact with
            data. When I am not coding, I am usually immersed in researching the
            latest trends in AI or conceptualizing new projects that could push
            the envelope even further. I am enthusiastic about opportunities
            that would allow me to collaborate on challenging projects, offering
            both my technical expertise and creative problem-solving skills.
          </p>
        </section>
        <h1 className="text-3xl font-bold my-4">My Projects</h1>

        <section className="bg-white bg-opacity-50 p-8 rounded-lg shadow-md">
          <h2 className="text-2xl font-semibold mb-2">Market Moment</h2>
          <p className="text-lg mb-4">
            Where a picture is worth a thousand words.
          </p>
          <Slider {...sliderSettings}>
            <div className="flex flex-col items-center">
              <img
                className="w-full h-100 object-cover rounded-lg mb-4"
                src="/MarketMomentHomePage.png"
                alt="Market moment home page"
              />
              <p className="text-md">
                Generate an image based representation of a stocks movement for
                that day.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <img
                className="w-full h-100 object-cover rounded-lg mb-4"
                src="/MarketMomentImagePromptGeneration.png"
                alt="Generated image displayed"
              />
              <p className="text-md">
                I use ChatGPT for text-to-image prompts.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <img
                className="w-full h-100 object-cover rounded-lg mb-4"
                src="/LightsaberExample.png"
                alt="Generated image displayed"
              />
              <p className="text-md">
                Stable Diffusion does the image generation.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <img
                className="w-full h-100 object-cover rounded-lg mb-4"
                src="/MarketMomentGenerationExample.png"
                alt="Generated image displayed"
              />
              <p className="text-md">
                Regenerating prompt results in different images.
              </p>
            </div>
            <div className="flex flex-col items-center">
              <img
                className="w-full h-100 object-cover rounded-lg mb-4"
                src="/PhoneExample.png"
                alt="Generated image displayed"
              />
              <p className="text-md">
                Hard for it to generate product images, results are mixed but
                interesting.
              </p>
            </div>
            {/* Add more images here */}
          </Slider>
        </section>
      </main>
    </>
  );
}
